# LABORATORIO 2
```{r}
library(nycflights13)
library(dplyr)
library(ggplot2)
library(tidyverse)
```
# Datasets
```{r}
View(weather)
View(flights)
View(planes)
View(airlines)
View(airports)
```
# 1. Inner join
## 1.1 Flights -> Planes
```{r}
flights %>%
  inner_join(planes, by= c("tailnum"="tailnum"), suffix = c("_flights", "_planes"))
```
## 1.2 Flights -> Airlines
```{r}
flights %>%
  inner_join(airlines, by= c("carrier"="carrier") , suffix = c("_flights", "_airlines"))
```
## 1.3 Fligths -> Airports
```{r}
flights %>%
  inner_join(airports, by= c("origin"="faa"), suffix = c("_flights", "_airports_origin")) %>%
  inner_join(airports, by= c("dest"="faa"), suffix = c("_flight", "_airports_dest"))
```
# 1.4 Flights -> Weather
```{r}
flights %>%
  inner_join(weather, by=c("year"="year", "month"="month", "day"="day", "hour"="hour", "origin"="origin"), suffix=c("_flights", "_weather")) 
```

# 2. Data manipulation
## 2.1 Conteo, filtro y arrange 
```{r}
flights %>%
  count(year, month, day) %>%
  filter(n > 1000) %>%
  arrange(n)
```
## 2.2 Seleccion
```{r}
flights_selected <- flights %>%
  select("year":"day", "hour", "origin", "dest", "tailnum", "carrier", "arr_delay", "dep_delay")
flights_selected
```
## 2.3 LeftJoin
```{r}
airlines %>%
  left_join(flights_selected, by=c("carrier"="carrier"), suffix=c("_airlines", "_flights")) %>%
  select(-"origin",-"dest") %>%
  mutate(tot_delay = arr_delay + dep_delay)

```
## 2.4 InnerJoin
```{r}
precip_delay <- flights %>%
  inner_join(weather) %>%
  group_by(precip) %>%
  summarise(delay = mean(dep_delay, na.rm = TRUE)) %>%
  mutate(delay = replace_na(delay,0))
  
precip_delay

```
## 2.5 Grafico
```{r}
ggplot(precip_delay, aes(x=precip, y=delay)) +geom_point()  + labs(title = "Precipitaciones vs Retraso") +xlab("Retraso") + ylab("Precipitaciones")
```
## 2.6 Filtros con areopuerto
```{r}
flights_airports <- flights %>% 
  filter(year==2013, month==5, day==10) %>%
  group_by(dest) %>%
  summarise(delay = mean(arr_delay,na.rm = TRUE)) %>%
  inner_join(airports, by=c("dest"="faa"))
flights_airports
  
```
## 2.7 Grafico de Lon,Lat
```{r}
ggplot(flights_airports, aes(x=lon,y=lat, color=delay, size=delay)) + geom_point() + labs(title = "Grafico de Longitud y Latitude") + xlab("Latitud") +ylab("Longitud")
```
## 2.8 InnerJoin con calculo de pi
```{r}
flights %>%
  inner_join(planes, by=c("tailnum"="tailnum"), suffix = c("_flights", "_planes")) %>%
  transmute("tailnum", "manufacturer", "pi" = (dep_delay + arr_delay)/air_time)
               
```

